// ─── MOCK DATA (kept as reference) ──────────────────────────────────────────
// This file previously contained hardcoded mock data for the dashboard.
// All dashboard data is now fetched dynamically from the backend via:
//   - StudyService.getUserDashboard()
//   - StudyService.getStudyStatistics(period)
//   - StudyService.getPerformanceAnalytics()
//
// The data flows through Redux (dashboardSlice) to DashboardScreen and its child components.
// ──────────────────────────────────────────────────────────────────────────────

/*
import { StudentData } from './types';

export const studentData: StudentData = {
  name: 'Priya Kumar',
  email: 'priya.kumar@example.com',
  studentId: 'STU2026001',
  avatar: 'https://ui-avatars.com/api/?name=Priya+Kumar&background=4a3728&color=f7f3ee&size=128',
  totalHours: 156,
  groupsJoined: 8,
  completedCoursesCount: 12,
  currentStreak: 15,
  joinedDate: 'Sep 2024',
  totalPoints: 2450,
  rank: 'Gold Member',
  averageScore: 91.25,
  weeklyGoal: 25,
  weeklyProgress: 18,

  studyTrend: [
    { day: 'Mon', hours: 3.5 },
    { day: 'Tue', hours: 4.2 },
    { day: 'Wed', hours: 2.8 },
    { day: 'Thu', hours: 5.1 },
    { day: 'Fri', hours: 3.9 },
    { day: 'Sat', hours: 6.2 },
    { day: 'Sun', hours: 4.0 },
  ],

  subjectShare: [
    { name: 'CS', value: 40, color: '#4a3728' },
    { name: 'Math', value: 25, color: '#8b6f47' },
    { name: 'Medical', value: 20, color: '#d4c4b5' },
    { name: 'Other', value: 15, color: '#6b8a73' },
  ],

  myCourses: [
    {
      id: 1,
      name: 'Advanced Data Structures',
      instructor: 'Dr. Rajesh Sharma',
      progress: 75,
      duration: '12 weeks',
      enrolled: 'Jan 2026',
      thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400&h=225&fit=crop',
      totalLessons: 48,
      completedLessons: 36,
      nextLesson: 'Trees and Graphs',
      difficulty: 'Advanced',
      rating: 4.8,
      students: 1245,
      lastAccessed: '2 hours ago',
      estimatedCompletion: '3 weeks',
      assignments: { completed: 8, total: 12 },
      quizzes: { completed: 6, total: 8 },
      watchTime: '32h 45m',
    },
    {
      id: 2,
      name: 'Machine Learning Fundamentals',
      instructor: 'Prof. Anita Desai',
      progress: 45,
      duration: '10 weeks',
      enrolled: 'Dec 2025',
      thumbnail: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=225&fit=crop',
      totalLessons: 40,
      completedLessons: 18,
      nextLesson: 'Neural Networks Basics',
      difficulty: 'Intermediate',
      rating: 4.9,
      students: 2156,
      lastAccessed: '1 day ago',
      estimatedCompletion: '5 weeks',
      assignments: { completed: 4, total: 10 },
      quizzes: { completed: 3, total: 8 },
      watchTime: '24h 20m',
    },
    {
      id: 3,
      name: 'Web Development Bootcamp',
      instructor: 'Arjun Mehta',
      progress: 90,
      duration: '8 weeks',
      enrolled: 'Nov 2025',
      thumbnail: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=400&h=225&fit=crop',
      totalLessons: 32,
      completedLessons: 29,
      nextLesson: 'Final Project Review',
      difficulty: 'Beginner',
      rating: 4.7,
      students: 3421,
      lastAccessed: '5 hours ago',
      estimatedCompletion: '1 week',
      assignments: { completed: 7, total: 8 },
      quizzes: { completed: 7, total: 8 },
      watchTime: '28h 15m',
    },
    {
      id: 4,
      name: 'Digital Marketing Strategy',
      instructor: 'Sneha Kapoor',
      progress: 30,
      duration: '6 weeks',
      enrolled: 'Jan 2026',
      thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=225&fit=crop',
      totalLessons: 24,
      completedLessons: 7,
      nextLesson: 'SEO Fundamentals',
      difficulty: 'Beginner',
      rating: 4.6,
      students: 1876,
      lastAccessed: '3 days ago',
      estimatedCompletion: '4 weeks',
      assignments: { completed: 2, total: 6 },
      quizzes: { completed: 1, total: 6 },
      watchTime: '8h 30m',
    },
  ],

  completedCourses: [
    {
      id: 1,
      name: 'Python Fundamentals',
      instructor: 'Dr. Vikram Singh',
      completedDate: 'Dec 15, 2024',
      score: 95,
      duration: '8 weeks',
      certificateId: 'CERT-PY-2024-001',
      thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=225&fit=crop',
      totalStudents: 2341,
      finalProject: 'E-commerce Backend API',
      skills: ['Python', 'Flask', 'SQLAlchemy', 'REST APIs'],
      certificateUrl: '/certificates/CERT-PY-2024-001',
    },
    {
      id: 2,
      name: 'React.js Masterclass',
      instructor: 'Prateek Narang',
      completedDate: 'Nov 22, 2024',
      score: 88,
      duration: '10 weeks',
      certificateId: 'CERT-RCT-2024-002',
      thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=225&fit=crop',
      totalStudents: 3125,
      finalProject: 'Social Media Dashboard',
      skills: ['React', 'Redux', 'TypeScript', 'Material-UI'],
      certificateUrl: '/certificates/CERT-RCT-2024-002',
    },
    {
      id: 3,
      name: 'Data Science Basics',
      instructor: 'Dr. Maya Patel',
      completedDate: 'Oct 10, 2024',
      score: 92,
      duration: '12 weeks',
      certificateId: 'CERT-DS-2024-003',
      thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=225&fit=crop',
      totalStudents: 1876,
      finalProject: 'Sales Prediction Model',
      skills: ['Pandas', 'NumPy', 'Scikit-learn', 'Matplotlib'],
      certificateUrl: '/certificates/CERT-DS-2024-003',
    },
    {
      id: 4,
      name: 'Database Management',
      instructor: 'Rahul Verma',
      completedDate: 'Sep 5, 2024',
      score: 90,
      duration: '6 weeks',
      certificateId: 'CERT-DB-2024-004',
      thumbnail: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400&h=225&fit=crop',
      totalStudents: 1543,
      finalProject: 'University Management System',
      skills: ['SQL', 'PostgreSQL', 'MongoDB', 'Database Design'],
      certificateUrl: '/certificates/CERT-DB-2024-004',
    },
  ],

  myGroups: [
    {
      id: 1,
      name: 'Data Structures Marathon',
      category: 'Computer Science',
      members: 45,
      progress: 75,
      nextSession: 'Today, 6:00 PM',
      sessionTopic: 'Binary Search Trees',
      active: true,
      meetingLink: 'https://meet.example.com/ds-marathon',
      leader: 'Amit Sharma',
      weeklyHours: 12,
      description: 'Intensive group focusing on mastering data structures',
      achievements: ['Top Performer', '100 Hour Club'],
      studyStreak: 21,
      totalSessions: 45,
      attendanceRate: 95,
    },
    {
      id: 2,
      name: 'NEET Biology Focus',
      category: 'Medical',
      members: 32,
      progress: 60,
      nextSession: 'Tomorrow, 4:00 PM',
      sessionTopic: 'Human Physiology',
      active: true,
      meetingLink: 'https://meet.example.com/neet-bio',
      leader: 'Dr. Kavita Reddy',
      weeklyHours: 15,
      description: 'Comprehensive NEET biology preparation',
      achievements: ['Perfect Attendance'],
      studyStreak: 15,
      totalSessions: 32,
      attendanceRate: 100,
    },
    {
      id: 3,
      name: 'JEE Advanced Math',
      category: 'Engineering',
      members: 28,
      progress: 85,
      nextSession: 'Today, 8:00 PM',
      sessionTopic: 'Calculus Applications',
      active: true,
      meetingLink: 'https://meet.example.com/jee-math',
      leader: 'Prof. Suresh Kumar',
      weeklyHours: 18,
      description: 'Advanced mathematics for JEE',
      achievements: ['Math Champion', 'Top Performer'],
      studyStreak: 28,
      totalSessions: 52,
      attendanceRate: 92,
    },
  ],

  upcomingSessions: [
    { id: 1, group: 'Data Structures Marathon', time: 'Today, 6:00 PM', topic: 'Binary Search Trees' },
    { id: 2, group: 'JEE Advanced Math', time: 'Today, 8:00 PM', topic: 'Calculus Applications' },
    { id: 3, group: 'NEET Biology Focus', time: 'Tomorrow, 4:00 PM', topic: 'Human Physiology' },
  ],

  upcomingCourseSessions: [
    { id: 1, course: 'Advanced Data Structures', time: 'Today, 3:00 PM', topic: 'Trees & Graphs Live' },
    { id: 2, course: 'Machine Learning Fundamentals', time: 'Tomorrow, 5:00 PM', topic: 'Neural Networks Workshop' },
    { id: 3, course: 'Web Development Bootcamp', time: 'Wednesday, 2:00 PM', topic: 'Final Project Review' },
  ],
};
*/